version: "3.3"
services:

    marketplace:
        environment:
            RECOMMENDATIONS_HOST: recommendations
        # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
        #                   -t marketplace --secret id=ca.key,src=ca.key
        image: arun33/marketplace-app-ssl:3cd36ee
        networks:
            - microservices
        ports:
            - 7001:5000

    recommendations:
        # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
        #                   -t recommendations --secret id=ca.key,src=ca.key
        image: arun33/recommendations-ssl-app:775bed2
        networks:
            - microservices

networks:
    microservices:
