---
- hosts: masters
  become: yes

  tasks:
  - name: update cache
    apt:
      update_cache: yes 
      upgrade: dist  
  - apt: name=apt-transport-https state=present
  - apt: name=gnupg2 state=present 
  - name: get the hostnames of the machines
    shell: 
      cmd: hostnamectl set-hostname master 
    register: node
  - debug: 
      var: node
  - name: install helpers packages
    shell:
      cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      warn: false
  - apt:
      deb: https://apt.kubernetes.io/ kubernetes-xenial main"

  - name: update packages
    apt:
      update_cache: yes
  - apt: name=kubectl state=present
  - apt: name=kubeadm state=present
  - apt: name=kubelet state=present
  - apt: name=kubernetes-cni state=present
  
  - apt: 
      name: docker.io
      state: present

  - name: add user to the group docker
    shell:
      cmd: usermod -aG docker $USER

  - name: setting the cgroup driver for kubernetes in docker configuration
    copy:
      src: ./file.txt
      dest: /etc/sysctl.d/k8s.conf
  - shell: 
      cmd: sysctl --system 
  - shell:
      cmd: kubeadm config images pull 
  - name: setting the cgroup driver for kubernetes in docker configuration
    copy:
      content: {"exec-opts": ["native.cgroupdriver=systemd"]} 
      dest: /etc/docker/daemon.json

  - shell:
      cmd: systemctl daemon-reload 
           
  - shell:  
      cmd: kubeadm init --apiserver-advertise-address="172.31.36.154" --pod-network-cidr="172.31.0.0/16" --ignore-preflight-errors=Mem,NumCPU
    register: result
  
  - debug:
      var: result
  
  - copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      remote_src: yes
      mode: 'preserve'
    become: yes
  

  - file:
      path: /home/ubuntu/.kube/config
      state: touch
      mode: u=rw,g=r,o=r
    become: yes
    shell:
      cmd: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      warn: false      
