---
- hosts: nodes
  become: yes

  tasks:
  - name: update packages on the kube-nodes group
    apt:
      update_cache: yes
  - apt:
      upgrade: dist
  - name: install dependencies packages
    apt: name=apt-transport-https state=present
  - apt: name=gnupg state=present  
  - apt: name=curl state=present
  - apt: name=lsb-release state=present
  - name: set the hostname of the node
    command: hostnamectl set-hostname k-node1
    register: result_nodename
  - debug:
      var: result_nodename['cmd'][2]
  - name: install kubernetes repositories
    shell:
      cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      warn: false
  - copy:
      content: deb https://apt.kubernetes.io/ kubernetes-xenial main
      dest: /etc/apt/sources.list.d/kubernetes.list
  - name: update the cached packages
    apt:
      update_cache: yes
  - name: install kubernetes main packages
    apt: name=kubectl state=present
  - apt: name=kubelet state=present
  - apt: name=kubeadm state=present
  - name: install containerd runtime for containers in the cluster 
    command: wget https://github.com/containerd/containerd/releases/download/v1.6.24/containerd-1.6.24-linux-amd64.tar.gz
  - name: uncompress the archive
    command: tar Czxvf /usr/local containerd-1.6.24-linux-amd64.tar.gz
  - name: start containerd service 
    command: wget https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
  - command: mv containerd.service /usr/lib/systemd/system/
  - command: systemctl daemon-reload
  - command: systemctl enable --now containerd
  - file:
      path: /etc/containerd/
      state: directory
  - file:
      path: /etc/containerd/config.toml
      state: touch
  - name: create containerd configuration file 
    shell: containerd config default >> /etc/containerd/config.toml
    args:
      chdir: /usr/local/bin/ 
  - shell:
      cmd: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
      warn: false
    register: mychanges
  - debug:
      var: mychanges
  - apt:
     update_cache: yes
  - name: install docker   
    apt: name=docker.io state=present
  - name: add user ubuntu to the group docker 
    user:
      name: ubuntu
      comment: user ubuntu
      uid: 1000
      groups: docker 
      append: yes 
    register: user_ubuntu
  - debug:
      var: user_ubuntu
  - copy:
      src: ./file.txt
      dest: /etc/sysctl.d/k8s.conf
  - command: sysctl --system
  - command: kubeadm join 192.168.1.183:6443 --token dr27lp.g2zon6gjvqc4in82 --discovery-token-ca-cert-hash sha256:514c94985e3af68c8f6350b974139a8fad871b6f9e28c456370ddb083fa8693e
    args:
      chdir: /home/ubuntu/
    register: myoutput
  - debug:
      var: myoutput
        