---
hosts: kube-nodes
ansible_user: ubuntu
become: yes

tasks:
- name: update packages on the kube-nodes group
  apt:
    update_cache: yes
    upgrade: dist
- name: install dependencies packages
- apt: name=apt-transport-https state=present
- apt: name=gnupg state=present  
- apt: name=curl state=present
- apt: name=lsb-release state=present
- name: set the hostname of the node
  shell:
    cmd: hostnamectl set-hostname k-node1
  register: result_nodename
- debug:
    var: result_nodename
- name: install kubernetes repositories
  shell:
    cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    warn: false
- copy:
    content: deb https://apt.kubernetes.io/ kubernetes-xenial main
    dest: /etc/apt/sources.list.d/kubernetes.list
- name: update the cached packages
- apt:
    update_cache: yes
- name: install kubernetes main packages
- apt: name=kubectl state=present
- apt: name=kubelet state=started
- apt: name=kubeadm state=present
- name: install containerd runtime for containers in the cluster 
  shell:
    cmd: wget https://github.com/containerd/containerd/releases/download/v1.6.24/containerd-1.6.24-linux-amd64.tar.gz
    warn: false
- shell: 
    cmd: tar Czxvf /usr/local containerd-1.6.24-linux-amd64.tar.gz
- shell:
    cmd: wget https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    warn: false
- shell:
    cmd: mv containerd.service /usr/lib/systemd/system/
- shell:
    cmd: systemctl daemon-reload
- shell:
    cmd: systemctl enable --now containerd
- file:
    path: /etc/containerd/
    state: directory
- shell:
    cmd: container config default |  tee /etc/containerd/config.toml
- lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^SystemdCgroup \='
    line: SystemdGroup = true
    state: present
    backrefs: yes
    register: mychanges
- debug:
    var: mychanges
- apt:
   update_cache: yes
- name: install docker   
- apt: name=docker.io state=present
- name: add user ubuntu to the group docker 
- user:
    name: ubuntu
    comment: user ubuntu
    uid: 1000
    groups: docker 
    append: yes 
    register: user_ubuntu
- debug:
    var: user_ubuntu['append'], user_ubuntu['groups']
- copy:
    src: ./file.txt
    dest: /etc/sysctl.d/k8s.conf
- command:
    argv:
      - sysctl --system
- reboot:
- command:
    argv:
      - kubeadm join 172.31.37.70:6443
      - --token j9irz3.4z5twnjwiblg0n24
      - --discovery-token-ca-cert-hash sha256:e0b9ef9d20344b5860140cf01086710f7771a19e79bded0b448b966a1adc253a
  args:
    chdir: /home/ubuntu/
  register: myoutput
        