apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: marketplace.digbot.fun
spec:
  secretName: marketplace.digbot.fun
  dnsNames:
  - marketplace.digbot.fun
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
