apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m2
  namespace: devops-tools
spec:
  storageClassName: aroon-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
